# Generated by Django 4.2.1 on 2023-09-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0004_article_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
