from .medicines import Medicines
from .employee import Employee
from .sale import Sale
from .category import Category
from .supplier import Supplier
from .article import Article
from .vacancy import Vacancy
from .faq import FAQ
from .review import Review
from .pharmacy_department import PharmacyDepartment
from .coupon import Coupon